### ISSUE TITLE
KeyError: 'force_color'

### ISSUE THREAD

**Issue by chrisspen** [kamilkijak/django-smoke-tests#18]
* django-smoke-tests version: 1.0.1
* Django version: 3.0
* Python version: 3.7
* Operating System: Ubuntu

### Description

I have have a Tox testing matrix running smoke_tests, and it's only failing for Django 3.0 with this strange error that doesn't touch any of my code:

    py37-django30 runtests: commands[0] | python manage.py smoke_tests
    Traceback (most recent call last):
      File "manage.py", line 12, in <module>
        execute_from_command_line(sys.argv)
      File ".tox/py37-django30/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
        utility.execute()
      File ".tox/py37-django30/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File ".tox/py37-django30/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
        self.execute(*args, **cmd_options)
      File ".tox/py37-django30/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
        if options['force_color'] and options['no_color']:
    KeyError: 'force_color'

Does this package support Django 3.0?

**Comment by AlertRED** [comment]
Same problem

**Comment by kamilkijak** [comment]
Thanks for reporting @chrisspen!

The `KeyError` has been solved in https://github.com/kamilkijak/django-smoke-tests/pull/13.

Django 3.2 LTS will be officially supported in the next release, the changes have been already added to the `master` branch (see https://github.com/kamilkijak/django-smoke-tests/pull/20). All tests are passing, but more verification is needed to make sure everything is working well.

**Comment by kamilkijak** [comment]
v2.0.0 has been released.
