### ISSUE TITLE
Problem with swapped user model

### ISSUE THREAD

**Issue by cyberbudy** [kamilkijak/django-smoke-tests#5]
There is a problem with a User model that has been swapped. 

I suppose the problem is because User is imported directly in the code, but instead should be imported with `get_user_model` function.

``` bash
Traceback (most recent call last):
  File "/home/cyberbudy/Workspace/Envs/server-svJPilQU/lib/python3.6/site-packages/django_smoke_tests/tests.py", line 22, in setUpClass
    cls.smoke_user = User.objects.create_superuser(
  File "/home/cyberbudy/Workspace/Envs/server-svJPilQU/lib/python3.6/site-packages/django/db/models/manager.py", line 190, in __get__
    cls._meta.swapped,
AttributeError: Manager isn't available; 'auth.User' has been swapped for 'staff.User'
```

**Comment by kamilkijak** [comment]
Thank you for reporting.

Good point, fixed in [0.4.1](https://github.com/kamilkijak/django-smoke-tests/releases/tag/v0.4.1)
